name: Publish to TestPyPI

on:
  push:
    branches: [main, dev ]

jobs:
  ci:
    uses: ./.github/workflows/python_ci.yml 

  test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TEST_PYPI_API_TOKEN }}
      run: |
        # Add timestamp to version for TestPyPI
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        sed -i "s/version = \".*\"/version = \"0.1.0.dev${TIMESTAMP}\"/" pyproject.toml
        twine upload --repository testpypi dist/* --verbose