name: Semantic Release

# Trigger only on push to main branch
on:
  push:
    branches: [ main ]
  workflow_call: # to allow trigger of this workflow from other workflows

jobs:
  # Call the CI workflow first
  ci:
    uses: ./.github/workflows/python_ci.yml # Uses a different workflow file
  
  release:
    runs-on: ubuntu-latest
    # Only run if CI tests pass
    needs: ci
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full history for semantic release
        fetch-depth: 0
        # Use personal access token for pushing tags (uncomment if using PAT)
        # token: ${{ secrets.PAT_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
        # Important: Allow the action to write back to the repo
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Run Semantic Release
      run: |
        # Create CHANGELOG.md if it doesn't exist
        if [ ! -f CHANGELOG.md ]; then
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "<!--next-version-->" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
        fi
        semantic-release version
        semantic-release publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}